1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [5]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([0, 2, 3, 4, 5])
arr3 = np.array([-1, 2, -3, 4, -5])  


print(f"Array 1: {arr1}")
print(f"Are all elements of Array 1 non-zero-> {np.all(arr1)}") 

print(f"\nArray 2: {arr2}")
print(f"Are all elements of Array 2 non-zero-> {np.all(arr2)}") 

print(f"\nArray 3: {arr3}")
print(f"Are all elements of Array 3 non-zero-> {np.all(arr3)}") 

Array 1: [1 2 3 4 5]
Are all elements of Array 1 non-zero-> True

Array 2: [0 2 3 4 5]
Are all elements of Array 2 non-zero-> False

Array 3: [-1  2 -3  4 -5]
Are all elements of Array 3 non-zero-> True


2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [7]:
import numpy as np

arr1 = np.array([0, 0, 0, 0, 0])
arr2 = np.array([0, 0, 1, 0, 0])
arr3 = np.array([-1, 0, -3, 0, -5])


print(f"Array 1: {arr1}")
print(f"Are all elements of Array 1 non-zero-> {np.any(arr1)}") 

print(f"\nArray 2: {arr2}")
print(f"Are all elements of Array 2 non-zero-> {np.any(arr2)}") 

print(f"\nArray 3: {arr3}")
print(f"Are all elements of Array 3 non-zero-> {np.any(arr3)}") 

Array 1: [0 0 0 0 0]
Are all elements of Array 1 non-zero-> False

Array 2: [0 0 1 0 0]
Are all elements of Array 2 non-zero-> True

Array 3: [-1  0 -3  0 -5]
Are all elements of Array 3 non-zero-> True


3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two
given

In [15]:
import numpy as np

array1 = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
array2 = np.array([1.0, 2.1, 3.0, 4.0, 5.1])

# comparison for  equality
exact_equal = array1 == array2

print("Exact equality comparison:\n", exact_equal)


# comparison for tolerance
tolerance = 0.5
close_equal = np.isclose(array1, array2, atol=tolerance)

print("Equality within tolerance comparison:\n", close_equal)

Exact equality comparison:
 [ True False  True  True False]
Equality within tolerance comparison:
 [ True  True  True  True  True]


4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [16]:
import numpy as np

z_arr = np.zeros(10)
o_arr = np.ones(10)
f_arr = np.full(10, 5)  

final_array = np.concatenate((z_arr, o_arr, f_arr))

print("The final resalte array", final_array)

Array of 10 zeros, 10 ones, and 10 fives:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [18]:
np.tile([0, 1, 5], 10)

array([0, 1, 5, 0, 1, 5, 0, 1, 5, 0, 1, 5, 0, 1, 5, 0, 1, 5, 0, 1, 5, 0,
       1, 5, 0, 1, 5, 0, 1, 5])

In [19]:
np.tile([0, 1, 5], 10).reshape(30)

array([0, 1, 5, 0, 1, 5, 0, 1, 5, 0, 1, 5, 0, 1, 5, 0, 1, 5, 0, 1, 5, 0,
       1, 5, 0, 1, 5, 0, 1, 5])

In [21]:
np.array([0] * 10 + [1] * 10 + [5] * 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5])

5. Write a NumPy program to create an array of the integers from 30 to70.

In [31]:
import numpy as np

arr1 = np.arange(30, 71)  
print("\nMethod 1 (range):\n",arr1)


arr2 = np.linspace(30, 70, 27, dtype=int) 
print("\nMethod 2 (linspace):\n", arr2)


arr3 = np.array(range(30, 71))
print("\nMethod 3 (array and range):\n", arr3)

arr4 = np.array([i for i in range(30, 71)])
print("\nMethod 4 (For and range):\n", arr4)


Method 1 (range):
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]

Method 2 (linspace):
 [30 31 33 34 36 37 39 40 42 43 45 46 48 50 51 53 54 56 57 59 60 62 63 65
 66 68 70]

Method 3 (array and range):
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]

Method 4 (For and range):
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


6. Write a NumPy program to create a 3x3 identity matrix

In [36]:
import numpy as np

identity_matrix1 = np.eye(3)
print("Method 1 (np.eye):\n", identity_matrix1)


identity_matrix2 = np.identity(3)
print("\nMethod 2 (np.identity):\n", identity_matrix2)


identity_matrix3 = np.array([[1, 0, 0],
                             [0, 1, 0],
                             [0, 0, 1]])
print("\nMethod 3 (manual creation):\n", identity_matrix3)



identity_matrix4 = np.diag([1, 1, 1])
print("\nMethod 4 (np.diag):\n", identity_matrix4)

Method 1 (np.eye):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Method 2 (np.identity):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Method 3 (manual creation):
 [[1 0 0]
 [0 1 0]
 [0 0 1]]

Method 4 (np.diag):
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


7. Write a NumPy program to generate a random number between 0 and 1

In [49]:
import numpy as np
import random as r


random_number1 = np.random.rand()
print("Method 1 (np.random.rand()):", random_number1)


random_number2 = np.random.random_sample()
print("\nMethod 2 (np.random.random_sample()):", random_number2)


random_number3 = np.random.uniform(0, 1)
print("\nMethod 3 (np.random.uniform()):", random_number3)


random_number4 = r.random()
print("\nMethod 4 (random.random()):", random_number4)

Method 1 (np.random.rand()): 0.8477489498287387

Method 2 (np.random.random_sample()): 0.6961267155751825

Method 3 (np.random.uniform()): 0.09620544016659416

Method 4 (random.random()): 0.18512296368260628


8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [51]:
import numpy as np


random_array1 = np.random.randn(15)  
print("Method 1 (np.random.randn):\n", random_array1)

random_array2 = np.random.normal(0, 1, 15)
print("\nMethod 2 (np.random.normal):\n", random_array2)

Method 1 (np.random.randn):
 [ 1.09062393 -0.86753157  1.03776274  1.49513649  0.41053281  0.10264982
  0.34876146 -0.34229307 -0.18213274 -2.01652733 -1.06145842 -0.45822636
 -1.11174207  0.48794674  1.41912798]

Method 2 (np.random.normal):
 [ 2.48147974  0.06602984 -1.04878894  0.70428947 -1.77793583  0.54556439
  0.66396356 -0.10078503 -0.20815387  0.1198388   0.16266411 -0.20163017
 -0.52980898 -1.05473722 -0.44014854]


9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [62]:
import numpy as np

my_vector = np.arange(15, 57)
print("Original vector:\n", my_vector)

print("\nValues except first and last (Method 1):\n", my_vector[1:-1])


my_vector2 = np.linspace(15, 57, 41, dtype=int)
print("\nOriginal vector:\n", my_vector2)

print("\nValues except first and last (Method 2):\n", my_vector2[1:-1])



my_vector3 = np.arange(15, 57)
print("\nOriginal vector:\n", my_vector3)

new_vector = my_vector3[1:len(my_vector3)-1] 
print("\nValues except first and last (Method 3):\n", new_vector)

Original vector:
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56]

Values except first and last (Method 1):
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]

Original vector:
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 57]

Values except first and last (Method 2):
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 36 37 38 39 40
 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]

Original vector:
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56]

Values except first and last (Method 3):
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [66]:
import numpy as np


random_vector1 = np.random.randint(0, 11, 5)  
print("Method 1 (np.random.randint):\n", random_vector1)


random_vector2 = np.random.choice(11, 5)
print("\nMethod 2 (np.random.choice):\n", random_vector2)


Method 1 (np.random.randint):
 [ 1  1  8  9 10]

Method 2 (np.random.choice):
 [ 1  6  0 10  5]


11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal
to 1, and inside 0.

In [69]:
import numpy as np

matrix = np.zeros((10, 10))

matrix[0, :] = 1          
matrix[-1, :] = 1        
matrix[:, 0] = 1          
matrix[:, -1] = 1         

print( matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
3, 4, 5.

In [80]:
import numpy as np


matrix1 = np.diag([1, 2, 3, 4, 5])
print("Method 1 (diag):\n", matrix1)


matrix3 = np.eye(5) * [1,2,3,4,5]
print("\nMethod 2 (eye and multiplication):\n", matrix3)


matrix = np.zeros((5, 5))
np.fill_diagonal(matrix, [1, 2, 3, 4, 5])
print("Method 3 fill_diagonal elements 1, 2, 3, 4, 5:\n", matrix)

Method 1 (diag):
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

Method 3 (eye and multiplication):
 [[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main
diagonal.

In [84]:
import numpy as np


matrix1 = np.zeros((4, 4), dtype=int)  
matrix1[::2, 1::2] = 1  
matrix1[1::2, ::2] = 1 

print("Method 1 (array creation and slicing):\n", matrix1)

Method 1 (array creation and slicing):
 [[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format)
and load it.

In [85]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

np.savez_compressed('arrays.npz', arr1=array1, arr2=array2)


loaded_data = np.load('arrays.npz')


loaded_array1 = loaded_data['arr1']
loaded_array2 = loaded_data['arr2']


print("Loaded Array 1:", loaded_array1)
print("Loaded Array 2:", loaded_array2)

Loaded Array 1: [1 2 3 4 5]
Loaded Array 2: [ 6  7  8  9 10]


15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.
Select

In [87]:
import numpy as np


random_array1 = np.random.rand(40)
print("Method 1 (np.random.rand):\n", random_array1)


random_array2 = np.random.randn(40)
print("\nMethod 2 (np.random.randn):\n", random_array2)


random_array3 = np.random.randint(0, 100, 40)
print("\nMethod 3 (np.random.randint):\n", random_array3)

Method 1 (np.random.rand):
 [0.95155461 0.45119014 0.64770472 0.47218657 0.43436147 0.80380996
 0.39453282 0.06847285 0.10992589 0.56960763 0.07411232 0.8357964
 0.3857958  0.99626771 0.68709737 0.10130454 0.02075787 0.05225225
 0.15926636 0.1401191  0.41916799 0.43761618 0.23526618 0.71660893
 0.31278083 0.34803004 0.92962879 0.03008335 0.18566098 0.37988402
 0.59899917 0.67870718 0.77969241 0.77377064 0.17264105 0.57644087
 0.7333306  0.27253939 0.30478853 0.4706309 ]

Method 2 (np.random.randn):
 [ 1.52193625 -2.57669198 -0.94577683 -1.31995572 -0.11612687 -0.70877583
 -1.616243    0.78531898  1.18693974 -0.93893667 -1.2794878   1.17021973
  0.7428471  -0.52958014 -0.70058832  1.71799195 -2.4406789   1.85816946
 -0.62527031 -0.64647023 -0.06531202  0.82870709 -0.16323617 -0.96372577
  1.05829047  0.48478617 -1.22465401  0.40765918  0.19125372  0.62613817
  1.81520958 -0.15030737  0.05218383  0.04696576 -0.11630198  0.46322071
  0.87877955 -1.04384602 -1.06841809 -0.09125985]

Method

16. Write a NumPy program to extract all numbers from a given array which are less and greater than a
specified number.

In [93]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

specified_number = 50


less_than = arr[arr < specified_number]

# Extract numbers greater than the specified number
greater_than = arr[arr >= specified_number]


print("Numbers less than 50 :", less_than)
print("Numbers greater than 50 :", greater_than)

Numbers less than 50 : [10 20 30 40]
Numbers greater than 50 : [ 50  60  70  80  90 100]
